version: '3.8'

services:
  # Backend BFF (Desenvolvimento)
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: development
    container_name: tmdb-api-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=${TMDB_BASE_URL:-https://api.themoviedb.org/3}
    volumes:
      - ./server:/app/server
      - /app/node_modules
    networks:
      - tmdb-network

  # Frontend (Desenvolvimento)
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
      target: development
    container_name: tmdb-web-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    depends_on:
      - api
    networks:
      - tmdb-network

networks:
  tmdb-network:
    driver: bridge


